# Generated by Django 2.1.7 on 2019-05-15 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor1', models.CharField(default='', max_length=30, null=True)),
                ('actor2', models.CharField(default='', max_length=30, null=True)),
                ('audiAcc', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(default='No Description', null=True)),
                ('director', models.CharField(default='', max_length=30, null=True)),
                ('movieNm', models.CharField(default='', max_length=100, null=True)),
                ('movieNmEn', models.CharField(default='', max_length=100, null=True)),
                ('openDt', models.CharField(default='', max_length=100, null=True)),
                ('posterUrl', models.TextField(default='', null=True)),
                ('videoUrl', models.CharField(default='', max_length=100, null=True)),
                ('sum_score', models.IntegerField(default=0, null=True)),
                ('count_score', models.IntegerField(default=0, null=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('review', models.CharField(max_length=1000)),
                ('value', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
